name: Docker CI for Docker Hub Pipeline

on:
  push:
    branches:
      - master

jobs:
  docker_build_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull existing Docker image
        run: |
          docker pull jayesh1209/website:base || echo "No existing base image found"

      - name: Build new Docker image
        run: |
          # Build a new image from the existing one
          docker build -t jayesh1209/website:${{ github.run_number }} \
            --build-arg BASE_IMAGE=jayesh1209/website:base .
          
          # Push the new image to Docker Hub
          docker push jayesh1209/website:${{ github.run_number }}
